<a href="https://colab.research.google.com/github/terrainthesky-hub/DS-Unit-4-Sprint-2-Neural-Networks/blob/main/module4-Hyperparameter-Tuning/Lesley_Rich_LS_DS_424_Hyperparameter_Tuning_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Hyperparameter Tuning

## *Data Science Unit 4 Sprint 2 Assignment 4*

## Your Mission, should you choose to accept it...

To hyperparameter tune and extract every ounce of accuracy out of this telecom customer churn dataset: [Available Here](https://lambdaschool-data-science.s3.amazonaws.com/telco-churn/WA_Fn-UseC_-Telco-Customer-Churn+(1).csv)

## Requirements

- Load the data
- Clean the data if necessary (it will be)
- Create and fit a baseline Keras MLP model to the data.
- Hyperparameter tune (at least) the following parameters:
 - batch_size
 - training epochs
 - optimizer
 - learning rate (if applicable to optimizer)
 - momentum (if applicable to optimizer)
 - activation functions
 - network weight initialization
 - dropout regularization
 - number of neurons in the hidden layer
 
 You must use Grid Search and Cross Validation for your initial pass of the above hyperparameters
 
 Try and get the maximum accuracy possible out of this data! You'll save big telecoms millions! Doesn't that sound great?

In [40]:
##### Your Code Here #####
#Sorry about the code comment vommit, it's late and I need to sleep but I got it working!

import pandas as pd

df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn+(1).csv')

In [ ]:
df.fillna(value='', inplace=True)

df.head()

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [ ]:
df.shape

(7043, 21)

In [41]:
import numpy as np
df = df.replace(np.NaN, 0)

In [42]:
df = df.replace({"Yes": 1, "No": 0, "No phone service": -1, " ": 0, "No internet service": -1})
nums = []

for i in df['TotalCharges']:
  nums.append(float(i))

df['Total_Charges'] = pd.Series(nums)

In [ ]:
df.head(50)

    gender  SeniorCitizen  Partner  ...  TotalCharges  Churn  Total_Charges
0   Female              0        1  ...         29.85      0          29.85
1     Male              0        0  ...        1889.5      0        1889.50
2     Male              0        0  ...        108.15      1         108.15
3     Male              0        0  ...       1840.75      0        1840.75
4   Female              0        0  ...        151.65      1         151.65
5   Female              0        0  ...         820.5      1         820.50
6     Male              0        0  ...        1949.4      0        1949.40
7   Female              0        0  ...         301.9      0         301.90
8   Female              0        1  ...       3046.05      1        3046.05
9     Male              0        0  ...       3487.95      0        3487.95
10    Male              0        1  ...        587.45      0         587.45
11    Male              0        0  ...         326.8      0         326.80
12    Male              0        1  ...        5681.1      0        5681.10
13    Male              0        0  ...        5036.3      1        5036.30
14    Male              0        0  ...       2686.05      0        2686.05
15  Female              0        1  ...       7895.15      0        7895.15
16  Female              0        0  ...       1022.95      0        1022.95
17    Male              0        0  ...       7382.25      0        7382.25
18  Female              0        1  ...        528.35      1         528.35
19  Female              0        0  ...        1862.9      0        1862.90
20    Male              1        0  ...         39.65      1          39.65
21    Male              0        1  ...        202.25      0         202.25
22    Male              0        0  ...         20.15      1          20.15
23  Female              0        1  ...        3505.1      0        3505.10
24    Male              0        1  ...        2970.3      0        2970.30
25  Female              0        0  ...        1530.6      0        1530.60
26    Male              0        1  ...       4749.15      1        4749.15
27    Male              0        1  ...          30.2      1          30.20
28    Male              0        1  ...       6369.45      0        6369.45
29  Female              0        0  ...        1093.1      1        1093.10
30  Female              1        1  ...       6766.95      0        6766.95
31    Male              1        1  ...        181.65      0         181.65
32  Female              0        1  ...       1874.45      0        1874.45
33    Male              0        0  ...          20.2      0          20.20
34    Male              1        0  ...         45.25      0          45.25
35  Female              0        1  ...        7251.7      0        7251.70
36    Male              0        0  ...         316.9      1         316.90
37  Female              0        0  ...        3548.3      0        3548.30
38    Male              0        0  ...       3549.25      1        3549.25
39  Female              0        0  ...        1105.4      1        1105.40
40    Male              0        1  ...         475.7      0         475.70
41  Female              0        1  ...       4872.35      0        4872.35
42  Female              0        1  ...        418.25      0         418.25
43  Female              0        0  ...       4861.45      0        4861.45
44  Female              0        1  ...        981.45      0         981.45
45  Female              0        0  ...        3906.7      0        3906.70
46    Male              0        0  ...            97      0          97.00
47  Female              0        0  ...        144.15      1         144.15
48    Male              0        0  ...        4217.8      0        4217.80
49  Female              0        1  ...        4254.1      0        4254.10

[50 rows x 21 columns]

In [43]:
df = df.drop(columns=['TotalCharges'], axis=1)

In [ ]:
df.dtypes

gender               object
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines         int64
InternetService      object
OnlineSecurity        int64
OnlineBackup          int64
DeviceProtection      int64
TechSupport           int64
StreamingTV           int64
StreamingMovies       int64
Contract             object
PaperlessBilling      int64
PaymentMethod        object
MonthlyCharges      float64
Churn                 int64
Total_Charges       float64
dtype: object

In [44]:
df['InternetService'] = df['InternetService'].replace(0, "None")
df = df.drop(columns=['customerID'])

In [45]:
categorical = ['gender', 'InternetService', 'Contract', 'PaymentMethod']
target = 'Churn'
features = df.columns.drop([target])


X_train = df[features]
y_train = df[target]

In [46]:
encoded_features = pd.get_dummies(X_train[categorical])

In [47]:
pd.concat([df, encoded_features], axis=1)

      gender  ...  PaymentMethod_Mailed check
0     Female  ...                           0
1       Male  ...                           1
2       Male  ...                           1
3       Male  ...                           0
4     Female  ...                           0
...      ...  ...                         ...
7038    Male  ...                           1
7039  Female  ...                           0
7040  Female  ...                           0
7041    Male  ...                           1
7042    Male  ...                           0

[7043 rows x 32 columns]

In [48]:
X_train = X_train.drop(columns=categorical)

In [ ]:

X_train.dtypes

SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines         int64
OnlineSecurity        int64
OnlineBackup          int64
DeviceProtection      int64
TechSupport           int64
StreamingTV           int64
StreamingMovies       int64
PaperlessBilling      int64
MonthlyCharges      float64
Total_Charges       float64
dtype: object

In [49]:
inputs = X_train.shape[1]

In [ ]:



# batch_size
# training epochs
# optimizer
# learning rate (if applicable to optimizer)
# momentum (if applicable to optimizer)
# activation functions
# network weight initialization
# dropout regularization
# number of neurons in the hidden layer

X_train.dtypes

gender               object
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling      int64
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
dtype: object

In [ ]:
# df['SeniorCitizen'] = df['SeniorCitizen'].astype(np.float32)
# df['Partner'] = df['Partner'].astype(np.float32)
# df['Dependents'] = df['Dependents'].astype(np.float32)
# df['tenure'] = df['tenure'].astype(np.float32)
# df['PhoneService'] = df['PhoneService'].astype(np.float32)
# df['PaperlessBilling'] = df['PaperlessBilling'].astype(np.float32)
# df['MonthlyCharges'] = df['MonthlyCharges'].astype(np.float32)
# df = df.drop(columns=['MultipleLines'])

In [13]:
inputs = X_train.shape[1]

In [14]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines         int64
InternetService      object
OnlineSecurity        int64
OnlineBackup          int64
DeviceProtection      int64
TechSupport           int64
StreamingTV           int64
StreamingMovies       int64
Contract             object
PaperlessBilling      int64
PaymentMethod        object
MonthlyCharges      float64
Churn                 int64
Total_Charges       float64
dtype: object

In [56]:
import numpy
import pandas as pd
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from keras import backend as K
#playing with batch size


def create_model():
    # create model
    model = Sequential()
    model.add(Dense(12, input_dim=inputs, activation='relu')),
    model.add(Dense(12, activation='relu')),
    model.add(Dense(1, activation='softmax'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0, validation_split=.2)

# define the grid search parameters
# batch_size = [10, 20, 40, 60, 80, 100]
# param_grid = dict(batch_size=batch_size, epochs=epochs)

# define the grid search parameters
param_grid = {'batch_size': [10, 20, 32],
              'epochs': [10]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Best: 0.2653713583946228 using {'batch_size': 10, 'epochs': 10}
Means: 0.2653713583946228, Stdev: 0.004757620185291315 with: {'batch_size': 10, 'epochs': 10}
Means: 0.2653713583946228, Stdev: 0.004757620185291315 with: {'batch_size': 20, 'epochs': 10}
Means: 0.2653713583946228, Stdev: 0.004757620185291315 with: {'batch_size': 32, 'epochs': 10}

In [57]:
from tensorflow.keras.optimizers import Adam
#Tweaking learning rate


def create_model(lr):
    #create optimizer
    adam = Adam(lr=lr)
    # create model
    
    model = Sequential()
    model.add(Dense(12, input_dim=inputs, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0, validation_split=0.2)

# define the grid search parameters
# batch_size = [10, 20, 40, 60, 80, 100]
# param_grid = dict(batch_size=batch_size, epochs=epochs)

# define the grid search parameters
param_grid = {'lr': [.001, .01, .1],
              'batch_size': [10],
              'epochs': [20]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, n_jobs=1)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Best: 0.7905721664428711 using {'batch_size': 10, 'epochs': 20, 'lr': 0.001}
Means: 0.7905721664428711, Stdev: 0.0005407159217730024 with: {'batch_size': 10, 'epochs': 20, 'lr': 0.001}
Means: 0.7810604174931844, Stdev: 0.006457182981954574 with: {'batch_size': 10, 'epochs': 20, 'lr': 0.01}
Means: 0.7346291939417521, Stdev: 0.004601525031331852 with: {'batch_size': 10, 'epochs': 20, 'lr': 0.1}

In [63]:
#Tweaking the network weight initializations 


from tensorflow.keras.optimizers import Adam
from tensorflow.keras import initializers
from tensorflow.keras import layers

def Merge(dict1, dict2): 
    param_grid = {**dict1, **dict2} 
    return param_grid 
  

init_mode = ['uniform', 'lecun_uniform', 'normal', 'zero', 'glorot_normal', 'glorot_uniform']    
param_grid1 = {'lr': [.001],
              'batch_size': [10],
              'epochs': [20]}
param_grid0 = dict(init_mode=init_mode)

param_grid = Merge(param_grid1, param_grid0)

def create_model(lr, init_mode='uniform'):
    #create optimizer
    adam = Adam(lr=lr)
    # create model

    model = Sequential()
    model.add(Dense(12, input_dim=inputs, kernel_initializer=init_mode, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0, validation_split=0.2)

# define the grid search parameters
# batch_size = [10, 20, 40, 60, 80, 100]
# param_grid = dict(batch_size=batch_size, epochs=epochs)

# define the grid search parameters


# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, n_jobs=1)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 



# def create_model(init_mode=init_mode):
#     #create optimizer
#     adam = Adam()
#     # create model
    
#     model = Sequential()
#     model.add(Dense(12, input_dim=inputs, kernel_initializer=init_mode, activation='relu'))
#     model.add(Dense(1, kernel_initializer=init_mode, activation='softmax'))
#     # Compile model
#     model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
#     return model

# # create model
# model = KerasClassifier(build_fn=create_model, verbose=0)

# # define the grid search parameters
# # batch_size = [10, 20, 40, 60, 80, 100]
# # param_grid = dict(batch_size=batch_size, epochs=epochs)

# # define the grid search parameters
# param_grid = dict(init_mode=init_mode)

# # param_grid = {'lr': [.001, .01, .1],
# #               'batch_size': [10],
# #               'epochs': [20]}

# # Create Grid Search
# grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
# grid_result = grid.fit(X_train, y_train)

# # Report Results
# print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
# means = grid_result.cv_results_['mean_test_score']
# stds = grid_result.cv_results_['std_test_score']
# params = grid_result.cv_results_['params']
# for mean, stdev, param in zip(means, stds, params):
#     print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Best: 0.7904305259386698 using {'batch_size': 10, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001}
Means: 0.7904305259386698, Stdev: 0.0019039238319379093 with: {'batch_size': 10, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001}
Means: 0.695698618888855, Stdev: 0.13763364318663607 with: {'batch_size': 10, 'epochs': 20, 'init_mode': 'lecun_uniform', 'lr': 0.001}
Means: 0.7207252581914266, Stdev: 0.06729183989026227 with: {'batch_size': 10, 'epochs': 20, 'init_mode': 'normal', 'lr': 0.001}
Means: 0.7346291939417521, Stdev: 0.004601525031331852 with: {'batch_size': 10, 'epochs': 20, 'init_mode': 'zero', 'lr': 0.001}
Means: 0.7688425779342651, Stdev: 0.029615026869372067 with: {'batch_size': 10, 'epochs': 20, 'init_mode': 'glorot_normal', 'lr': 0.001}
Means: 0.7553640007972717, Stdev: 0.044507888052802876 with: {'batch_size': 10, 'epochs': 20, 'init_mode': 'glorot_uniform', 'lr': 0.001}

In [66]:


from tensorflow.keras.optimizers import Adam
from tensorflow.keras import initializers
from tensorflow.keras import layers
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from keras.constraints import maxnorm


def Merge(dict1, dict2): 
    param_grid = {**dict1, **dict2} 
    return param_grid 
  

init_mode = ['uniform']    
param_grid1 = {'lr': [.001],
              'batch_size': [10],
              'epochs': [20]}
param_grid0 = dict(init_mode=init_mode)

param_grid4 = Merge(param_grid1, param_grid0)

weight_constraint = [1, 2, 3]
dropout_rate = [0.0, 0.1, 0.2]

param_grid3 = dict(dropout_rate=dropout_rate, weight_constraint=weight_constraint)

param_grid = Merge(param_grid4, param_grid3)

def create_model(lr, init_mode='uniform', dropout_rate=0.0, weight_constraint=0):
    #create optimizer
    adam = Adam(lr=lr)
    # create model

    model = Sequential()
    model.add(Dense(12, input_dim=inputs, kernel_initializer='uniform', activation='relu', kernel_constraint=maxnorm(weight_constraint)))
    model.add(Dropout(dropout_rate))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0, validation_split=0.2)

# def create_model(dropout_rate=0.0, weight_constraint=0):
#     #create optimizer
#     adam = Adam()
#     # create model
    
#     model = Sequential()
#     model.add(Dense(12, input_dim=inputs, kernel_initializer='uniform', activation='relu', kernel_constraint=maxnorm(weight_constraint)))
#     model.add(Dropout(dropout_rate))
#     model.add(Dense(1, kernel_initializer='uniform', activation='softmax'))
#     # Compile model
#     model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
#     return model
# weight_constraint = [1, 2, 3, 4, 5]
# dropout_rate = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

# param_grid3 = dict(dropout_rate=dropout_rate, weight_constraint=weight_constraint)
# # define the grid search parameters
# # batch_size = [10, 20, 40, 60, 80, 100]
# # param_grid = dict(batch_size=batch_size, epochs=epochs)

# # define the grid search parameters


# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, n_jobs=1)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 



# def create_model(dropout_rate=0.0, weight_constraint=0):
#     #create optimizer
#     adam = Adam()
#     # create model
    
#     model = Sequential()
#     model.add(Dense(12, input_dim=inputs, kernel_initializer='uniform', activation='relu'))
#     model.add(Dropout(.02))
#     model.add(Dense(1, kernel_initializer='uniform', activation='softmax'))
#     # Compile model
#     model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
#     return model
# weight_constraint = [1, 2, 3, 4, 5]
# dropout_rate = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]


# # create model
# model = KerasClassifier(build_fn=create_model, verbose=0)

# # define the grid search parameters
# # batch_size = [10, 20, 40, 60, 80, 100]
# # param_grid = dict(batch_size=batch_size, epochs=epochs)

# # define the grid search parameters
# # param_grid = dict(init_mode=init_mode)

# # param_grid = {'lr': [.001, .01, .1],
# #               'batch_size': [10],
# #               'epochs': [20]}

# # Create Grid Search
# grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
# grid_result = grid.fit(X_train, y_train)

# # Report Results
# print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
# means = grid_result.cv_results_['mean_test_score']
# stds = grid_result.cv_results_['std_test_score']
# params = grid_result.cv_results_['params']
# for mean, stdev, param in zip(means, stds, params):
#     print(f"Means: {mean}, Stdev: {stdev} with: {param}") 


# #Activation, testing dropout too

# activation = ['softmax', 'sigmoid', 'hard_sigmoid']

# def create_model(activation='relu'):
#     #create optimizer
#     adam = Adam()
#     # create model
    
#     model = Sequential()
#     model.add(Dense(12, input_dim=inputs, kernel_initializer='uniform', activation=activation))
#     model.add(Dropout(.2)) 
#     model.add(Dense(1, kernel_initializer='uniform', activation=activation))
#     # Compile model
#     model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
#     return model

# # create model
# model = KerasClassifier(build_fn=create_model, verbose=0)

# # define the grid search parameters
# # batch_size = [10, 20, 40, 60, 80, 100]
# # param_grid = dict(batch_size=batch_size, epochs=epochs)

# # define the grid search parameters
# param_grid = dict(activation=activation)

# # param_grid = {'lr': [.001, .01, .1],
# #               'batch_size': [10],
# #               'epochs': [20]}

# # Create Grid Search
# grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
# grid_result = grid.fit(X_train, y_train)

# # Report Results
# print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
# means = grid_result.cv_results_['mean_test_score']
# stds = grid_result.cv_results_['std_test_score']
# params = grid_result.cv_results_['params']
# for mean, stdev, param in zip(means, stds, params):
#     print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Best: 0.78957599401474 using {'batch_size': 10, 'dropout_rate': 0.0, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'weight_constraint': 1}
Means: 0.78957599401474, Stdev: 0.01167722749908377 with: {'batch_size': 10, 'dropout_rate': 0.0, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'weight_constraint': 1}
Means: 0.7829051613807678, Stdev: 0.0042414678794312054 with: {'batch_size': 10, 'dropout_rate': 0.0, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'weight_constraint': 2}
Means: 0.7766591310501099, Stdev: 0.0128672161390183 with: {'batch_size': 10, 'dropout_rate': 0.0, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'weight_constraint': 3}
Means: 0.7769412597020467, Stdev: 0.004450270436287022 with: {'batch_size': 10, 'dropout_rate': 0.1, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'weight_constraint': 1}
Means: 0.7890108029047648, Stdev: 0.002194428313793873 with: {'batch_size': 10, 'dropout_rate': 0.1, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'weight_constraint': 2}
Means: 0.7681328852971395, Stdev: 0.028267365720204673 with: {'batch_size': 10, 'dropout_rate': 0.1, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'weight_constraint': 3}
Means: 0.7742444078127543, Stdev: 0.00420518244886341 with: {'batch_size': 10, 'dropout_rate': 0.2, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'weight_constraint': 1}
Means: 0.7655835747718811, Stdev: 0.021355746789198878 with: {'batch_size': 10, 'dropout_rate': 0.2, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'weight_constraint': 2}
Means: 0.7689933975537618, Stdev: 0.021988082566957324 with: {'batch_size': 10, 'dropout_rate': 0.2, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'weight_constraint': 3}

In [68]:
#tuning neurons
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import initializers
from tensorflow.keras import layers
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from keras.constraints import maxnorm


def Merge(dict1, dict2): 
    param_grid = {**dict1, **dict2} 
    return param_grid 
  

init_mode = ['uniform']    
param_grid1 = {'lr': [.001],
              'batch_size': [10],
              'epochs': [20]}
param_grid0 = dict(init_mode=init_mode)

param_grid4 = Merge(param_grid1, param_grid0)

weight_constraint = [1]
dropout_rate = [0.0]

param_grid3 = dict(dropout_rate=dropout_rate, weight_constraint=weight_constraint)

param_grid5 = Merge(param_grid4, param_grid3)

neurons = [1,15,12,20,35]
param_grid6 = dict(neurons=neurons)

param_grid = Merge(param_grid5, param_grid6)


def create_model(lr, init_mode='uniform', dropout_rate=0.0, weight_constraint=0, neurons=1):
    #create optimizer
    adam = Adam(lr=lr)
    # create model

    model = Sequential()
    model.add(Dense(neurons, input_dim=inputs, kernel_initializer='uniform', activation='relu', kernel_constraint=maxnorm(weight_constraint)))
    model.add(Dropout(dropout_rate))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0, validation_split=0.2)


# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, n_jobs=1)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 




# def create_model(lr, neurons=1):
#     #create optimizer
#     adam = Adam(lr=lr)
#     # create model
    
#     model = Sequential()
#     model.add(Dense(12, input_dim=inputs, kernel_initializer='uniform', activation='relu'))
#     model.add(Dense(12, activation='relu'))
#     model.add(Dense(1, kernel_initializer='uniform', activation='softmax'))
#     # Compile model
#     model.compile(loss='sparse_categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
#     return model

# def Merge(dict1, dict2): 
#     param_grid = {**dict1, **dict2} 
#     return param_grid 


# # param_grid0 = dict(neurons=neurons)
# param_grid = {'lr': [.01],
#               'batch_size': [32],
#               'epochs': [20]}
              
# # param_grid = Merge(param_grid0, param_grid1)
# # create model
# model = KerasClassifier(build_fn=create_model, verbose=0)

# # define the grid search parameters
# # batch_size = [10, 20, 40, 60, 80, 100]
# # param_grid = dict(batch_size=batch_size, epochs=epochs)

# # define the grid search parameters
# # param_grid = dict(init_mode=init_mode)



# # Create Grid Search
# grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
# grid_result = grid.fit(X_train, y_train)

# # Report Results
# print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
# means = grid_result.cv_results_['mean_test_score']
# stds = grid_result.cv_results_['std_test_score']
# params = grid_result.cv_results_['params']
# for mean, stdev, param in zip(means, stds, params):
#     print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Best: 0.7909982999165853 using {'batch_size': 10, 'dropout_rate': 0.0, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'neurons': 20, 'weight_constraint': 1}
Means: 0.7535185615221659, Stdev: 0.022147877672510398 with: {'batch_size': 10, 'dropout_rate': 0.0, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'neurons': 1, 'weight_constraint': 1}
Means: 0.7767979502677917, Stdev: 0.009302333596823422 with: {'batch_size': 10, 'dropout_rate': 0.0, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'neurons': 15, 'weight_constraint': 1}
Means: 0.7725359201431274, Stdev: 0.021801878722515045 with: {'batch_size': 10, 'dropout_rate': 0.0, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'neurons': 12, 'weight_constraint': 1}
Means: 0.7909982999165853, Stdev: 0.0018980779717470886 with: {'batch_size': 10, 'dropout_rate': 0.0, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'neurons': 20, 'weight_constraint': 1}
Means: 0.7733944853146871, Stdev: 0.02681091387776008 with: {'batch_size': 10, 'dropout_rate': 0.0, 'epochs': 20, 'init_mode': 'uniform', 'lr': 0.001, 'neurons': 35, 'weight_constraint': 1}

In [39]:

def create_model():
    # create model
    model = Sequential()
    model.add(Dense(12, input_dim=inputs, activation='relu')),
    model.add(Dense(12, activation='relu')),
    model.add(Dense(1, activation='softmax'))
    # Compile model
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

# define the grid search parameters
# batch_size = [10, 20, 40, 60, 80, 100]
# param_grid = dict(batch_size=batch_size, epochs=epochs)

# define the grid search parameters
param_grid = {'batch_size': [10, 20, 32, 40, 60],
              'epochs': [20]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Best: 0.0 using {'batch_size': 10, 'epochs': 20}
Means: 0.0, Stdev: 0.0 with: {'batch_size': 10, 'epochs': 20}
Means: 0.0, Stdev: 0.0 with: {'batch_size': 20, 'epochs': 20}
Means: 0.0, Stdev: 0.0 with: {'batch_size': 32, 'epochs': 20}
Means: 0.0, Stdev: 0.0 with: {'batch_size': 40, 'epochs': 20}
Means: 0.0, Stdev: 0.0 with: {'batch_size': 60, 'epochs': 20}

In [ ]:
!pip install keras-tuner

Collecting keras-tuner
  Downloading https://files.pythonhosted.org/packages/a7/f7/4b41b6832abf4c9bef71a664dc563adb25afc5812831667c6db572b1a261/keras-tuner-1.0.1.tar.gz (54kB)
     |████████████████████████████████| 61kB 3.5MB/s
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from keras-tuner) (0.16.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from keras-tuner) (1.18.5)
Requirement already satisfied: tabulate in /usr/local/lib/python3.6/dist-packages (from keras-tuner) (0.8.7)
Collecting terminaltables
  Downloading https://files.pythonhosted.org/packages/9b/c4/4a21174f32f8a7e1104798c445dacdc1d4df86f2f26722767034e4de4bff/terminaltables-3.1.0.tar.gz
Collecting colorama
  Downloading https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from keras-tuner) (4.41.1)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from keras-tuner) (2.23.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from keras-tuner) (1.4.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from keras-tuner) (0.22.2.post1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->keras-tuner) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->keras-tuner) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->keras-tuner) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->keras-tuner) (2.10)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->keras-tuner) (0.16.0)
Building wheels for collected packages: keras-tuner, terminaltables
  Building wheel for keras-tuner (setup.py) ... done
  Created wheel for keras-tuner: filename=keras_tuner-1.0.1-cp36-none-any.whl size=73200 sha256=2ee626cccd87a62a0c6cbe226361ed33e82a5db4a723c5bbf960000ac4566594
  Stored in directory: /root/.cache/pip/wheels/b9/cc/62/52716b70dd90f3db12519233c3a93a5360bc672da1a10ded43
  Building wheel for terminaltables (setup.py) ... done
  Created wheel for terminaltables: filename=terminaltables-3.1.0-cp36-none-any.whl size=15356 sha256=54dbe59cc17150fc3736c97c117cfb977c420cd63122959c3e17cd777ca1fb71
  Stored in directory: /root/.cache/pip/wheels/30/6b/50/6c75775b681fb36cdfac7f19799888ef9d8813aff9e379663e
Successfully built keras-tuner terminaltables
Installing collected packages: terminaltables, colorama, keras-tuner
Successfully installed colorama-0.4.3 keras-tuner-1.0.1 terminaltables-3.1.0

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers
from kerastuner.tuners import RandomSearch

"""
This model Tunes:
- Number of Neurons in the Hidden Layer
- Learning Rate in Adam

"""

def build_model(hp):
    model = keras.Sequential()
    model.add(layers.Dense(units=hp.Int('units',
                                        min_value=32,
                                        max_value=512,
                                        step=32), activation='relu'))
    model.add(layers.Dense(1))
    model.compile(
        optimizer=keras.optimizers.Adam(
            hp.Choice('learning_rate',
                      values=[1e-2, 1e-3, 1e-4])),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy'])
    
    return model

In [ ]:
tuner = RandomSearch(
    build_model,
    objective='accuracy',
    max_trials=5,
    executions_per_trial=3,
    directory='./keras-tuner-trial',
    project_name='hyperparameter_tuning_assignment')

In [ ]:
# categorical_features = ['gender', 'MultipleLines', 'InternetService', 'Contract', 'PaymentMethod']

# one_hot_encoder = OneHotEncoder(sparse=False)
# one_hot_encoder.fit(X_train[categorical_features])

# X_train_encoded = one_hot_encoder.transform(X_train[categorical_features])

TypeError: ignored

customerID          7043
gender              7043
SeniorCitizen       7043
Partner             7043
Dependents          7043
tenure              7043
PhoneService        7043
MultipleLines       7043
InternetService     7043
OnlineSecurity      7043
OnlineBackup        7043
DeviceProtection    7043
TechSupport         7043
StreamingTV         7043
StreamingMovies     7043
Contract            7043
PaperlessBilling    7043
PaymentMethod       7043
MonthlyCharges      7043
TotalCharges        7043
Churn               7043
dtype: int64

## Stretch Goals:

- Try to implement Random Search Hyperparameter Tuning on this dataset
- Try to implement Bayesian Optimiation tuning on this dataset using hyperas or hyperopt (if you're brave)
- Practice hyperparameter tuning other datasets that we have looked at. How high can you get MNIST? Above 99%?
- Study for the Sprint Challenge
 - Can you implement both perceptron and MLP models from scratch with forward and backpropagation?
 - Can you implement both perceptron and MLP models in keras and tune their hyperparameters with cross validation?